### ISSUE TITLE
IC7: iRacing Support

### ISSUE THREAD

**Issue by ccdpiljek** [Blumlaut/simhub-dashes#4]
Do you have any plans to add iRacing support for the IC7 dash?
Thank you so much for your hard work!
David

**Comment by Blumlaut** [comment]
I personally don't play iRacing, please provide a simhub replay which goes through scenarios the dash would usually display, I can add support for all missing parameters then

**Comment by Blumlaut** [comment]
closing this due to no reply, please provide a replay if you want me to add iRacing support.
